# Generated by Django 2.1.5 on 2019-01-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asdf', models.TextField(help_text='asdf 헬텍', max_length=100)),
                ('ttt', models.TextField(help_text='이건 헬프텍스트', max_length=50)),
            ],
        ),
    ]
